public class TriggerFrameworkConstants {

    public static String NULLVALUE ='';
    public static Final String HelperAlreadyExisting='Helper Already Existing';
    public static Final String TriggerAlreadyExisting='Trigger Already Existing';
    public static Final String HelperCreated='Helper creation initiated. Please verify in classes screen after a while';
    public static Final String TriggerCreated='Trigger creation initiated.Please verify in triggers screen after a while';
    public static Final String UnderscoreTrigger='_Trigger';
    public static Final String UnderscoreUnderscoreC='__c';
    public static Final String No_beginTrans_called_for='No beginTrans() called for';
    public static Final String Enter_Exit_Mismatch='enter/exit mismatch';
    public static Final String Exit_Called_Without_Enter='exit called without enter';
    public static Final String Enter_Not_Called='enter not called';
    public static Final String Invalid_Combintn_Of_Triggr_Paramtrs='invalid combination of trigger parameters';
    public static Final String Underscore='_';
    public static Final String Helper='Helper';
    public static Final String Triggr='Trigger';
    public static Final String Message='message';
    public static Final String State='state';
    public static Final String Error='error';
    public static Final String Config_Deleted='Configuration Deleted';
    public static Final String Success='success';
    public static Final String Somethng_went_wrng_pls_try_again='Something Went Wrong Please Try Again';
    public static Final String Endpoint_Class='/services/data/v41.0/sobjects/ApexClass';
    public static Final String Endpoint_Trigger='/services/data/v41.0/sobjects/ApexTrigger';
    public static Final String POST='POST';
    public static Final String Content_Type='Content-Type';
    public static Final String application_json='application/json';
    public static Final String Authorization='Authorization';
    public static Final String OAuth='OAuth ';
    public static Final String Saved_Successfully='Saved Successfully';
    public static Final String Config_Created_Successfully='Configuration Created Successfully';
    public static Final String Config_Binded_To_Profile='Configuration Binded To Profile';
    public static Final String configData='configData';
    public static Final String profileList='profileList';
    public static Final String ActiveProfileIds='activeProfileIds';
    public static Final String SplitBy='[,]{1}[\\s]?';
    
}